#!/usr/bin/env csh

#=========================================================================#
#   Job setup script for the tide initial condition
#=========================================================================#

# Here we just set up a state at rest with linear stratification b = Y:
./tide
