program tide

use constants

! This routine sets up a state at rest with b = Y.

implicit double precision (a-h,o-z)

 !Local vorticity and buoyancy arrays:
double precision:: zz(0:ny,0:nxm1),bb(0:ny,0:nxm1)

 !Read Y from coords.r8, generated by conform.f90, and assign to b:
open(20,file='coords.r8',form='unformatted', &
    & access='direct',status='old',recl=2*nbytes)
read(20,rec=2) t,bb
close(20)

 !Set zeta = 0:
zz=0.d0

 !Write vorticity distribution to file:
open(20,file='zz_init.r8',form='unformatted', &
    & access='direct',status='replace',recl=2*nbytes)
write(20,rec=1) zero,zz
close(20)

 !Write buoyancy distribution to file:
open(20,file='bb_init.r8',form='unformatted', &
    & access='direct',status='replace',recl=2*nbytes)
write(20,rec=1) zero,bb
close(20)

end program
