#!/usr/bin/env csh

#============================================================================#
# Job setup script for an elliptical vortex with a parabolic PV distribution
#============================================================================#
set datagen = "ellipse"

# Data generation routine specific parameters:
set a  =  "1.8"    # Major semi-axis length
set b =   "0.6"    # Minor semi-axis length

#==========================================================================
echo ' The PV inside the vortex (x^2/a^2 + y^2/b^2 < 1) is given by'
echo ' q = 4*pi*(1 - x^2/a^2 - y^2/b^2).'

echo -n ' Semi-major axis length, a (default' $a')? '
set var=$<
if ($var != "") set a=$var

echo -n ' Semi-minor axis length, b (default' $b')? '
set var=$<
if ($var != "") set b=$var

echo '  Ellipse with a PV distribution' >> job_info
echo '  q = 4*pi*(1 - x^2/a^2 - y^2/b^2)' >> job_info
echo ' ' >> job_info
echo '  Semi-major axis length, a:         ' $a >> job_info
echo '  Semi-minor axis length, b:         ' $b >> job_info

cat << /EOF > in_$datagen
$a $b
/EOF

$datagen < in_$datagen > out_$datagen
