#!/usr/bin/env csh

#=====================================================#
# Job setup script for narrow-band initial conditions
#=====================================================#

narrow > out_narrow
