#!/usr/bin/env csh

#=========================================================================#
#    Runs dataview on any selected field in the evolution subdirectory
#=========================================================================#

set n=$#argv

if ($n == 0) then
   echo
   echo '  Usage:   dv <field> <options>'
   echo
   echo '  Examples:'
   echo
   echo '  dv qq1'
   echo '  dv qq1 -lims -0.001 0.001'
   echo '  dv qq1 -notitle -cb'
   echo
   echo '  (For all options, just type "dataview")'
   echo
   exit (-1)
else
   set field=$1
endif

# Get resolution
set nx = `grep "nx=" src/parameters.f90 | awk -F= '{print $(NF)}'`
set ny = `grep "ny=" src/parameters.f90 | awk -F= '{print $(NF)}'`
@ ny = ( $ny + 1 )

if ($n != 1) then
   # Remove first element of argument list <field> to get <options>:
   shift
   dataview -ndim $nx $ny {evolution/}$field{.r4} $argv &
else
   dataview -ndim $nx $ny {evolution/}$field{.r4} &
endif
