#!/usr/bin/env python

# This script plots up the spectra output from a main casl run.
# Some help on further options can be obtained by running:
# sv -h

#=====perform the various imports========
#=======needed by the main code==========
import sys,os,warnings
# Define main hydra tree locations:
uname=os.getlogin()
homedir=os.getenv('HOME')
rootdir=os.path.join(homedir,'hydra','scripts')
moddir=os.path.join(rootdir,'modules')
graphicsdir=os.path.join(rootdir,'graphics')
sys.path.append(moddir)
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as clrs
# Set default plot save resolution to a large value:
mpl.rcParams['savefig.dpi'] = 800
import argparse
warnings.simplefilter("ignore",DeprecationWarning)

#========================================
#=====various function definitions=======
#========================================

def parse_args():
  # Define a parser and read in the command line arguments passed when the script is run.
  parser = argparse.ArgumentParser(prog='spec_view')
  # Argument list:
  # Default limits for the spectra are -5, 3. 
  # this can be over-ridden with this option:
  parser.add_argument('-ylims', metavar='y_lim' , type=float , nargs=2, default='-5.0 3.0'.split(),help='Lower and upper limits for y range of the plot')
  args = parser.parse_args() 
  # Return a parsed argument object:
  return args

def running(args):
  # Main code opening and controlling a plotting window.

  # Open input file:
  try:
     in_file=open('spectra/qspec.asc','r') # try opening qspec.asc
  except IOError, message:# error if file not found 
     print >> sys.stderr, 'qspec.asc does not exist!', message
     sys.exit()

  # Read the first header line to get kmax:
  first_line=in_file.readline()  
  kmax=int(first_line.split()[-1])
  in_file.seek(0)

  # Read in the full data to a 1d array and close input file:
  raw_data = np.fromfile(file=in_file,dtype=float,sep='\n')
  in_file.close()

  # Set the number of frames:
  nframes = int(len(raw_data)/(3*kmax+6))  
  print 'Number of frames found %i' %nframes

  # Shape the data array into a useful shape for plotting:
  frames=range(0,nframes)
  tim_eles = [i*(3*kmax+6)+j for i in frames for j in range(6)]
  shaped_data = np.delete(raw_data,tim_eles)[0:(3*kmax+6)*nframes].reshape((nframes,kmax,3))
  global ic 
  # Grab the correct sub-array for plotting (ic is the current frame)  
  ic = 0
  # Initiate a plotting window and plot relevant data into it:
  fig = plt.figure(1)
  ax = fig.add_subplot(111)
  im = ax.plot(shaped_data[ic].transpose()[0],shaped_data[ic].transpose()[1],'r-',label='bt PV spectrum')
  im2 = ax.plot(shaped_data[ic].transpose()[0],shaped_data[ic].transpose()[2],'b-',label='bc PV spectrum')
  # Set plot title, legend and limits of the plot:
  ax.set_title('Frame no.: '+str(ic+1))
  ax.legend()
  ylimits=[float(y) for y in args.ylims]
  ax.set_xlim(shaped_data[ic].transpose()[0].min(),shaped_data[ic].transpose()[0].max())
  ax.set_ylim(ylimits)

  def on_press(event):
    # Routine to deal with re-plotting the window on keypress. 
    # The keys -/= (ie. -/+ without the shift key) cycle through frames 
    # forward and backwards.
    global ic
    if event.key=='=':
      axes=event.canvas.figure.get_axes()[0]
      ic = (ic+1+nframes) % nframes
      xlim=axes.get_xlim()
      ylim=axes.get_ylim()
      # Clear the axes for replot:
      axes.clear()
      # Replot the relevant data:
      axes.plot(shaped_data[ic].transpose()[0],shaped_data[ic].transpose()[1],'r-',label='bt PV spectrum')
      axes.plot(shaped_data[ic].transpose()[0],shaped_data[ic].transpose()[2],'b-',label='bc PV spectrum')
      # Set the title, legend and plot limits:
      axes.set_title('Frame no.: '+str(ic+1))
      axes.legend()
      axes.set_xlim(xlim)  
      axes.set_ylim(ylim)
      plt.draw()
    if event.key=='-':
      axes=event.canvas.figure.get_axes()[0]
      ic = (ic-1+nframes) % nframes
      xlim=axes.get_xlim()
      ylim=axes.get_ylim()
      # Clear the axes for replot:
      axes.clear()
      # Replot the relevant data:
      axes.plot(shaped_data[ic].transpose()[0],shaped_data[ic].transpose()[1],'r-',label='bt PV spectrum')
      axes.plot(shaped_data[ic].transpose()[0],shaped_data[ic].transpose()[2],'b-',label='bc PV spectrum')
      # Set the title, legend and plot limits:
      axes.set_title('Frame no.: '+str(ic+1))
      axes.legend()
      axes.set_xlim(xlim)  
      axes.set_ylim(ylim)
      # Finally redraw the plot:
      plt.draw()

  # Begin the plot and link keypress events to the above handler:
  cid=fig.canvas.mpl_connect('key_press_event',on_press)
  plt.show()
 

if __name__ == '__main__':
  # Main code to drive the above routines:
  args = parse_args()
  running(args)



