#!/usr/bin/env csh

#=========================================================================#
#   Job setup script for the slug initial condition
#=========================================================================#
set datagen = "slug"

# Set fixed constants:
set pi=3.14159265358979
set twopi=`echo "scale=10; 2 * $pi" | bc -l`

#==========================================================================
# Defaults:
set width=1.0
set height=0.5
set trans=0.02

echo ' We start with a slug of fluid of higher density.'
echo -n ' Width of the higher density zone (default' $width')?'
set var=$<
if ($var != "") set width=$var
echo -n ' Height of the higher density zone (default' $height')? '
set var=$<
if ($var != "") set height=$var
echo -n ' Width of the density transition zone (default' $trans')? '
set var=$<
if ($var != "") set trans=$var

echo ' ' >> job_info
echo ' Slug width:                         ' $width >> job_info
echo ' Slug height:                        ' $height >> job_info
echo ' Slug density transition length:     ' $trans >> job_info

cat << /EOF > in_$datagen
$width 
$height
$trans
/EOF

$datagen < in_$datagen > out_$datagen
