#!/usr/bin/env csh

#=========================================================================#
#    Runs dataview on any selected field in the evolution subdirectory
#    The data are assumed to projected orthographically using "ortho".
#=========================================================================#

set n=$#argv

if ($n == 0) then
   echo
   echo '  Usage:   odv <field> <options>'
   echo
   echo '  Examples:'
   echo
   echo '  odv qqop'
   echo '  odv qqop -lims -0.001 0.001'
   echo '  odv qqop -notitle -cb'
   echo
   echo '  (For all options, just type "dataview")'
   echo
   exit (-1)
else
   set field=$1
endif

# Get resolution
set ng = `grep "ng=" src/parameters.f90 | awk -F= '{print $(NF-1)}' | awk -F, '{print $1}'`

if ($n != 1) then
   # Remove first element of argument list <field> to get <options>:
   shift
   dataview -ndim $ng $ng {evolution/}$field{.r4} $argv &
else
   dataview -ndim $ng $ng {evolution/}$field{.r4} &
endif
