#!/usr/bin/env csh

#=========================================================================#
#   Job setup script for a state of rest
#=========================================================================#
set datagen = "rest"

#==========================================================================
echo ' ' >> job_info
echo ' Starting from q = 2*Omega*sin(latitude)' >> job_info

$datagen
