#!/usr/bin/env csh

#=========================================================================#
#   Job setup script for a buoyancy strip
#=========================================================================#
set datagen = "vstrip"

# Data generation routine specific parameters:
set wid  =  "0.7"      # Meridional width of strip in the domain
set amp  =  "0.01"     # Amplitude of disturbance (see below)
set k    =  "2"        # Wavenumber of disturbance (see below)

#==========================================================================
echo ' We start with a strip of buoyancy of width w and having a cross-sectional'
echo ' distribution b(y) = sqrt(1 - 4*y^2/w^2) for |y| < w/2.'

echo -n ' Width of the strip, w (default' $wid')? '
set var=$<
if ($var != "") set wid=$var

echo ' The bouyancy perturbation is 2*A*s*(1-s^2)*sin(k*x) where s = 2*y/w.'
echo -n ' Enter A (default' $amp')? '
set var=$<
if ($var != "") set amp=$var

echo -n ' Enter k (default' $k')? '
set var=$<
if ($var != "") set k=$var

echo '  Bouyancy strip; width, w:          ' $wid >> job_info
echo ' ' >> job_info
echo '  Pertubation: 2*A*s*(1-s^2)*sin(k*x) where s = 2*y/w' >> job_info
echo '     Amplitude, A:                   ' $amp >> job_info
echo '     Wavenumber, k:                  ' $k >> job_info

cat << /EOF > in_$datagen
$wid
$amp $k
/EOF

$datagen < in_$datagen > out_$datagen
