#!/usr/bin/env csh

#=========================================================================#
#   Job setup script for the Random forcing case
#=========================================================================#
set datagen = "rest-state"

$datagen 
